//  世界很大，却很少能有人记得曾经对你好，付出的那些人。
//  走在前面的那个人就只会看到更前方，都挺忙的，谁有时间往后看呢？
//  能在开源里写鸣谢前辈的人的人真的是少之又少.
//  每个人都有高光时刻和平庸之时，但愿这漫长人生，我们都不负自己。

// RaceSpeedTime
// 版权所有 2020 RaceSpeedTime(YuCarl77) 保留所有权利。
// RaceSpeedTime 的诞生离不开 5F(自由居民区) 开源项目以及其他开源脚本/插件和作者。

// RST团队服务器开发主要由[R_ST]Hygen（YuCarl77）领导

// 自己需要更加强大，才不会受外人影响
// 在过去自己没技术，有求于他人却时常遭到一些令人不齿的回应。
// 例如过去我们有求于他人架设服务器，却遭到非常攻击性的回应。
// 现在，我们自从2020年1月已经只靠自身公益，不接受捐赠，不求于他人。
// 相较于某些友商，我们学习了linux,nodejs,mysql等等，提高自身知识储备。
// 既然不愿帮助，那我们就自身努力。
// 每向前一步，都是在刀尖上跳舞，这个圈子从来都不是和平的。

// Credits
// 特别感谢
// 下列不分顺序先后

// Take-Two https://www.take2games.com Interactive Leading Game Publisher | Take-Two Interactive
// Rockstar Games https://www.rockstargames.com
// Grand theft auto: San Andreas
// SA:MP https://www.sa-mp.com
// SA:MP FORUM https://forum.sa-mp.com
// GTAUN https://github.com/GTAUN https://www.gtaun.net
// GTABBS https://www.gtabbs.com - 分享的责任与获取的自由
// SAMP吧
// 5F(自由居民区)
// 7F(未来世界) https://github.com/yzz/gta-sa-mp_wl
// 兰草乡村(Dylan时期)
// 技术帮助及OBJ指导 ryddawn(范冬梅) [Fire]KiVen JoshenKM
// 拍摄现场
// 酷派天空
// 自由城
// 狂野之城
// PRace
// PHouse
// Goods_Sys(Episodes KiVen juse)
// [Ghost]Rui
// ushio_p
// [Ghost]Dylan
// [ITC]dyq 
// [ITC]fangye
// [ITC]Super_wlc
// [ITC]RR_LXD 
// mk124 https://github.com/mk124
// Shindo(aka. ssh)
// vvg
// yezizhu(aka. yzz)
// questionAnswer
// Attire
// Camera
// DeathMatch
// billboard
// 维度 https://tieba.baidu.com/home/main?un=li123856
// 自由者(全系列)
// ASAN https://github.com/KrYpToDeN/Advanced-SA-NickName
// strlib https://github.com/oscar-broman/strlib
// Zeex Pawn compiler v3.10.10 https://github.com/pawn-lang/compiler
// markski1 https://github.com/markski1/MRKS-3D-Speedometer
// Anti_Cheat RogueDrifter https://github.com/RogueDrifter/Anti_cheat_pack
// streamer https://github.com/samp-incognito/samp-streamer-plugin
// sscanf https://github.com/maddinat0r/sscanf
// SAMPMailJS https://github.com/bruxo00/SAMPMailJS
// MySQL https://github.com/pBlueG/SA-MP-MySQL
// NodeJS https://nodejs.org
// Timer-Fix https://github.com/KashCherry/Timer-Fix-plugin
// samp-plugin-timerfix https://github.com/YuCarl77/samp-plugin-timerfix
// 无名汉化组 - https://wmhhz.com
// SA-MP-FileManager https://github.com/JaTochNietDan/SA-MP-FileManager
// PAWN vsCode extension
// EasyDialog https://github.com/Awsomedude/easyDialog
// mkstr
// (Jochemd)TimestampToDate https://forum.sa-mp.com/showthread.php?t=347605
// Improved ZCMD https://forum.sa-mp.com/showthread.php?t=576114
// Zeex zcmd 0.3.1 | Fast & Simple Command Processor https://forum.sa-mp.com/showthread.php?t=91354
// sscanf https://forum.sa-mp.com/showthread.php?t=570927
// crashdetect https://github.com/Zeex/samp-plugin-crashdetect
// Alternative Anti-DeAMX using emit https://forum.sa-mp.com/showthread.php?t=267957
// mSelection https://forum.sa-mp.com/showthread.php?t=407045
// 优雅的耍赖基(https://space.bilibili.com/434982170)
// iconv-lite https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.2.tgz
// http https://registry.npmjs.org/http/-/http-0.0.0.tgz
// fs https://registry.npmjs.org/fs/-/fs-0.0.1-security.tgz
// nodemailer https://registry.npmjs.org/nodemailer/-/nodemailer-6.3.0.tgz
// punycode https://registry.npmjs.org/punycode/-/punycode-1.3.2.tgz
// querystring https://registry.npmjs.org/querystring/-/querystring-0.2.0.tgz
// safer-buffer https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz
// url https://registry.npmjs.org/url/-/url-0.11.0.tgz
// Fly Camera(Gammix) https://forum.sa-mp.com/showthread.php?t=589766



//  本服修改自5F，Prace,PHouse,Goods等开源 特别鸣谢：[Ghost]Rui ushio_p [Ghost]Dylan
//  致敬自由居民区开源,制作者:[ITC]dyq  [ITC]fangye  [ITC]Super_wlc [ITC]RR_LXD  mk124  Shindo(aka. ssh)  vvg, yezizhu(aka. yzz)
//  特别鸣谢 ryddawn 技术及OBJ指导；[Fire]KiVen JoshenKM
//  特别鸣谢 GoodsSys开发者Episodes KiVen juse
//  特别鸣谢 GTAUN GTABBS 
//  This server is modified from 5F free residential open source, Prace open source
//  To the makers of Prace:[Ghost]Rui ushio_p [Ghost]Dylan
//  Tribute to the makers of the free settlement :[ITC]dyq [ITC]fangye [ITC]Super_wlc [ITC]RR_LXD  mk124  Shindo(aka. ssh)  vvg, yezizhu(aka. yzz)
//  Special thanks to ryddawn and technical advisor [Fire]KiVen OBJ:JoshenKM;